apiVersion: v1
kind: Pod
metadata:
  name: postgress-app-pod
  labels:
    name: postgress-app-pod
    app: demo-app
spec:
  containers:
    - name: postgress-app
      image: postgress:9.4
      ports:
        - containerPort: 5432
